# Random Forest Classifier & its Comparison of Hotel Booking Pridictions

In [3]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from folium.plugins import HeatMap
import plotly.express as px

In [4]:
# reading data
df = pd.read_csv('hotel_bookings.csv')
df.head(20)

           hotel  is_canceled  ...  reservation_status  reservation_status_date
0   Resort Hotel            0  ...           Check-Out               2015-07-01
1   Resort Hotel            0  ...           Check-Out               2015-07-01
2   Resort Hotel            0  ...           Check-Out               2015-07-02
3   Resort Hotel            0  ...           Check-Out               2015-07-02
4   Resort Hotel            0  ...           Check-Out               2015-07-03
5   Resort Hotel            0  ...           Check-Out               2015-07-03
6   Resort Hotel            0  ...           Check-Out               2015-07-03
7   Resort Hotel            0  ...           Check-Out               2015-07-03
8   Resort Hotel            1  ...            Canceled               2015-05-06
9   Resort Hotel            1  ...            Canceled               2015-04-22
10  Resort Hotel            1  ...            Canceled               2015-06-23
11  Resort Hotel            0  ...           Check-Out               2015-07-05
12  Resort Hotel            0  ...           Check-Out               2015-07-05
13  Resort Hotel            0  ...           Check-Out               2015-07-05
14  Resort Hotel            0  ...           Check-Out               2015-07-05
15  Resort Hotel            0  ...           Check-Out               2015-07-05
16  Resort Hotel            0  ...           Check-Out               2015-07-05
17  Resort Hotel            0  ...           Check-Out               2015-07-02
18  Resort Hotel            0  ...           Check-Out               2015-07-02
19  Resort Hotel            0  ...           Check-Out               2015-07-05

[20 rows x 32 columns]

In [5]:
df.describe()

         is_canceled  ...  total_of_special_requests
count  119390.000000  ...              119390.000000
mean        0.370416  ...                   0.571363
std         0.482918  ...                   0.792798
min         0.000000  ...                   0.000000
25%         0.000000  ...                   0.000000
50%         0.000000  ...                   0.000000
75%         1.000000  ...                   1.000000
max         1.000000  ...                   5.000000

[8 rows x 20 columns]

In [6]:
# chek info about data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [14]:
# checking for null values
null = pd.DataFrame({'Null Values: ':df.isnull().sum(), 'Null Percentage: ': (df.isnull().sum()/df.shape[0]) * 100})
print(null)
# checking percentage of null values

                                Null Values:   Null Percentage:
hotel                                       0           0.000000
is_canceled                                 0           0.000000
lead_time                                   0           0.000000
arrival_date_year                           0           0.000000
arrival_date_month                          0           0.000000
arrival_date_week_number                    0           0.000000
arrival_date_day_of_month                   0           0.000000
stays_in_weekend_nights                     0           0.000000
stays_in_week_nights                        0           0.000000
adults                                      0           0.000000
children                                    4           0.003350
babies                                      0           0.000000
meal                                        0           0.000000
country                                   488           0.408744
market_segment                              0           0.000000
distribution_channel                        0           0.000000
is_repeated_guest                           0           0.000000
previous_cancellations                      0           0.000000
previous_bookings_not_canceled              0           0.000000
reserved_room_type                          0           0.000000
assigned_room_type                          0           0.000000
booking_changes                             0           0.000000
deposit_type                                0           0.000000
agent                                   16340          13.686238
company                                112593          94.306893
days_in_waiting_list                        0           0.000000
customer_type                               0           0.000000
adr                                         0           0.000000
required_car_parking_spaces                 0           0.000000
total_of_special_requests                   0           0.000000
reservation_status                          0           0.000000
reservation_status_date                     0           0.000000

In [15]:
# filling null values with zero
df.fillna(0, inplace=True)

In [16]:
df.shape

(119390, 32)

In [17]:
# adults, babies and children can't be zero at same time, so drop
filter = (df.children == 0) & (df.adults == 0) & (df.babies == 0)
df[filter]

               hotel  is_canceled  ...  reservation_status  reservation_status_date
2224    Resort Hotel            0  ...           Check-Out               2015-10-06
2409    Resort Hotel            0  ...           Check-Out               2015-10-12
3181    Resort Hotel            0  ...           Check-Out               2015-11-23
3684    Resort Hotel            0  ...           Check-Out               2016-01-04
3708    Resort Hotel            0  ...           Check-Out               2016-01-05
...              ...          ...  ...                 ...                      ...
115029    City Hotel            0  ...           Check-Out               2017-06-30
115091    City Hotel            0  ...           Check-Out               2017-07-01
116251    City Hotel            0  ...           Check-Out               2017-07-17
116534    City Hotel            0  ...           Check-Out               2017-07-22
117087    City Hotel            0  ...           Check-Out               2017-07-29

[180 rows x 32 columns]

In [18]:
df = df[~filter]
df

               hotel  is_canceled  ...  reservation_status  reservation_status_date
0       Resort Hotel            0  ...           Check-Out               2015-07-01
1       Resort Hotel            0  ...           Check-Out               2015-07-01
2       Resort Hotel            0  ...           Check-Out               2015-07-02
3       Resort Hotel            0  ...           Check-Out               2015-07-02
4       Resort Hotel            0  ...           Check-Out               2015-07-03
...              ...          ...  ...                 ...                      ...
119385    City Hotel            0  ...           Check-Out               2017-09-06
119386    City Hotel            0  ...           Check-Out               2017-09-07
119387    City Hotel            0  ...           Check-Out               2017-09-07
119388    City Hotel            0  ...           Check-Out               2017-09-07
119389    City Hotel            0  ...           Check-Out               2017-09-07

[119210 rows x 32 columns]

In [19]:
df[filter]

C:\Users\asad\AppData\Local\Temp\ipykernel_1536\1940024178.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[filter]

Empty DataFrame
Columns: [hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, company, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date]
Index: []

In [20]:
df.shape

(119210, 32)

# Explotary Data Analysis

from where the most guests are coming?

In [ ]:
# selecting country wise guests is_canceled == 0
country_wise_guests = df[df['is_canceled'] == 0] ['country'].value_counts
country_wise_guests.